FROM chriszero/ubuntu-s6-base
MAINTAINER chriszero <zerov83@gmail.com>

# Dataonly Container

# VDR
VOLUME /etc/vdr
VOLUME /vdr/config
VOLUME /vdr/cache

#EPGD
VOLUME /epgd/config

# MariaDB / MySQL
VOLUME /var/lib/mysql

CMD ["true"]
